version: '3'
 services:
   httpd:
     image: httpd:latest
     container_name: my-website-1
     volumes:
       - /home/ec2-user/html:/usr/local/apache2/htdocs
     ports:
      - "80:80"
   nginx:
    image: nginx:latest
    container_name: my-website-2
    build: .
    volumes:
      - "volum:/usr/share/nginx/html/"
    ports:
     - "8999:8080"
   tomcat:
     image: tomcat:latest
     build: ./test/
     container_name: my-website-3
     ports:
      - "7888:8090"
 volumes:
   volum:
